added get_pdf method
minimul/qbo_api pull request #135
Opened 2024-06-10 17:40 UTC by Greyoxide

Hi this is my first ever pull request so let me know if I've done something wrong.

I've implemented a `get_pdf`method as described in [issue number 62](https://github.com/minimul/qbo_api/issues/62).  I've also added a test to the test suite which tests this new method against the invoices endpoint.  I've also tested the new method against the development mode on my production app by downloading a pdf copy of an invoice, estimate, and purchase order.

In addition to the `get_pdf` method appended to `qbo_api/api_methods.rb`, I've also adjusted the response method found in `connection.rb`.  Given that application/json is the default content type, I've added a check to determine if this case is an exception to the default content type.

2024-06-12 10:09 UTC, minimul commented
I will review within the next week.

2024-06-15 11:40 UTC, minimul commented
OK. This looks fine.

Next week, I'm going to test it more thoroughly.

In the meantime, if you could implement my comments.

Thank you.

2024-06-15 11:42 UTC, minimul commented on lib/qbo_api/connection.rb
> +      puts headers
Remove.

2024-06-22 13:05 UTC, minimul requested changes

2024-06-24 23:55 UTC, Greyoxide commented on spec/api_methods_spec.rb
> +        pdf_starts_correctly = !!(result =~ /^%PDF-\d+(\.\d+)?/)
good call, I've updated this spec to use `.match` to check for the pdf content response

2024-07-01 22:18 UTC, minimul commented on lib/qbo_api/connection.rb
> +        # headers are an optional argument
We don't need the comments. Please remove them here and in the spec.

2024-07-02 11:26 UTC, minimul commented on spec/api_methods_spec.rb
> +        # Ensure result is not nil and is a pdf stream
Remove.

2024-07-09 12:03 UTC, minimul commented
I'll take a look soon.

2024-07-23 13:07 UTC, minimul commented
I'll be taking a look this week.

2024-07-27 11:45 UTC, merged

2024-07-27 11:47 UTC, minimul commented
Merged and released in 3.0.3.